### ISSUE TITLE
New Program: Stony Brook University

### ISSUE THREAD

**Issue by Dededon** [fhbzc/CSS_program#18]
Name of the Program:
Stony Brook University PhD in Sociology
IACS Graduate Fellowship

Link to the Official Website:
https://www.stonybrook.edu/commcms/sociology/graduate/phd.php

https://iacs.stonybrook.edu/opportunities/fellowships/Graduate-Fellowships

Comment:
Scholars: 
Yongjun Zhang https://yongjunzhang.com
Jason Jeffrey Jones https://jasonjones.ninja
CSSERG Lab: https://jasonjones.ninja/csserg/

**Comment by fhbzc** [comment]
Thank you for the information, I have added them and closed the issue for now
