### ISSUE TITLE
Taiwanese researcher in CSS

### ISSUE THREAD

**Issue by himanlin** [fhbzc/CSS_program#19]
Yen-Sheng Chiang (Academia Sinica, Taiwan)
https://www.ios.sinica.edu.tw/pi.php?id=134&typeID=100

Mu-Jung Cho (Academia Sinica, Taiwan)
https://www.rchss.sinica.edu.tw/members/4a08ea44-a61a-4425-acc5-95fe06e67a32?page_id=45

Chen-Shou Hong (National Taiwan University, Taiwan)
https://sociology.ntu.edu.tw/en/faculty/chen-shuo-hong/?doing_wp_cron=1729805326.3883159160614013671875

Ming-Yi Chang (Fu Jen Catholic University, Taiwan)
https://www.soci.fju.edu.tw/teacher_detail.php?id=526

Ji-Lung Hsieh National Taiwan University, Taiwan)
http://www.journalism.ntu.edu.tw/Journalism/fulltime-2.html

Chen-Yi Yu (Kaohsiung Medical University, Taiwan)
https://gigs.kmu.edu.tw/index.php/en-gb/專任教師/32-english-web/faculty/602-chen-yi-yu

Hsuan-Wei "Wayne" Lee (Lehigh University, USA)
https://sites.google.com/view/hsuanweilee/home

Yuan Hsiao (Yale University, USA)
https://sociology.yale.edu/people/yuan-hsiao

**Comment by fhbzc** [comment]
Thank you for the information, I have added them and closed the issue for now
