### ISSUE TITLE
Computational Social Scientists

### ISSUE THREAD

**Issue by leechihyu** [fhbzc/CSS_program#20]
Yuki Shiraito, UMichi
https://lsa.umich.edu/polisci/people/faculty/shiraito.html

Daniel Hopkins, UPenn
https://live-sas-www-polisci.pantheon.sas.upenn.edu/people/standing-faculty/daniel-hopkins

Dean Knox, UPenn
https://oid.wharton.upenn.edu/profile/dcknox/

Naijia Liu, Harvard
https://www.gov.harvard.edu/directory/naijia-liu/

Melissa Dell, Harvard
https://dell-research-harvard.github.io/

Kenneth Benoit, Singapore Management University
https://kenbenoit.net/

Francisco Cantu, University of Houston
https://franciscocantu.github.io

**Comment by fhbzc** [comment]
Thank you for the info. Added and closed the issue for now
